// SPDX-License-Identifier: 0BSD

using Windows.Win32.System.Threading;

namespace Vezel.Ruptura.System;

public enum PriorityLevel : int
{
    Idle = THREAD_PRIORITY.THREAD_PRIORITY_IDLE,
    Lowest = THREAD_PRIORITY.THREAD_PRIORITY_LOWEST,
    BelowNormal = THREAD_PRIORITY.THREAD_PRIORITY_BELOW_NORMAL,
    Normal = THREAD_PRIORITY.THREAD_PRIORITY_NORMAL,
    AboveNormal = THREAD_PRIORITY.THREAD_PRIORITY_ABOVE_NORMAL,
    Highest = THREAD_PRIORITY.THREAD_PRIORITY_HIGHEST,
    TimeCritical = THREAD_PRIORITY.THREAD_PRIORITY_TIME_CRITICAL,
}
