using Windows.Win32.System.Threading;

namespace Vezel.Ruptura.System;

[Flags]
public enum ThreadAccess : uint
{
    Terminate = THREAD_ACCESS_RIGHTS.THREAD_TERMINATE,
    SuspendResume = THREAD_ACCESS_RIGHTS.THREAD_SUSPEND_RESUME,
    GetContext = THREAD_ACCESS_RIGHTS.THREAD_GET_CONTEXT,
    SetContext = THREAD_ACCESS_RIGHTS.THREAD_SET_CONTEXT,
    SetInfo = THREAD_ACCESS_RIGHTS.THREAD_SET_INFORMATION,
    GetInfo = THREAD_ACCESS_RIGHTS.THREAD_QUERY_INFORMATION,
    SetLimitedInfo = THREAD_ACCESS_RIGHTS.THREAD_SET_LIMITED_INFORMATION,
    GetLimitedInfo = THREAD_ACCESS_RIGHTS.THREAD_QUERY_LIMITED_INFORMATION,
    Synchronize = THREAD_ACCESS_RIGHTS.THREAD_SYNCHRONIZE,
}
